'use client';

import React, { useState, useEffect, useRef } from 'react';
import { UploadCloud, MessageSquare, Star, UserCheck, FileText, ArrowRight, ArrowLeft, Send, FileDown, RefreshCcw, Loader2 } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { sendForumMessage, getForumMessages, getAllGroupsList, getGroupData } from '../actions';
import jsPDF from 'jspdf'; 

type ForumMessage = {
  _id: string;
  groupName: string;
  userName: string;
  message: string;
  createdAt: string;
};

export default function PresentasiPage() {
  const router = useRouter();
  const [groupName, setGroupName] = useState('');
  const [userName, setUserName] = useState('');
  
  // State Presentasi
  const [isGenerating, setIsGenerating] = useState(false);
  const [isUploaded, setIsUploaded] = useState(false);
  
  // State Data Realtime
  const [otherGroups, setOtherGroups] = useState<string[]>([]);
  const [peerScore, setPeerScore] = useState<{ [key: string]: number }>({});
  const [forumMessages, setForumMessages] = useState<ForumMessage[]>([]);
  
  // Chat Input
  const [newComment, setNewComment] = useState('');
  
  // PERBAIKAN: Gunakan Ref untuk Container, bukan elemen akhir
  const chatContainerRef = useRef<HTMLDivElement>(null);

  // 1. Inisialisasi Data
  useEffect(() => {
    const initData = async () => {
        const sessionStr = localStorage.getItem('gi_session');
        if (sessionStr) {
            const parsed = JSON.parse(sessionStr);
            setGroupName(parsed.groupName);
            
            // PERBAIKAN DI SINI: Gunakan parsed.userName
            setUserName(parsed.userName || 'Anggota Anonim');

            const allGroups = await getAllGroupsList();
            const others = allGroups.filter((g: string) => g !== parsed.groupName);
            setOtherGroups(others);
        }
    };
    initData();
  }, []);

  // 2. Polling Live Forum
  useEffect(() => {
    const fetchForum = async () => {
        const msgs = await getForumMessages();
        // Cek apakah ada pesan baru untuk menghindari render berlebihan
        setForumMessages((prev) => {
            if (prev.length !== msgs.length) return msgs;
            return prev; 
        });
    };
    fetchForum(); 
    const interval = setInterval(fetchForum, 3000); 
    return () => clearInterval(interval);
  }, []);

  // PERBAIKAN: Auto-scroll HANYA di dalam container, tidak mengganggu window utama
  useEffect(() => {
    if (chatContainerRef.current) {
        const { scrollHeight, clientHeight } = chatContainerRef.current;
        // Scroll ke bawah container chat
        chatContainerRef.current.scrollTo({
            top: scrollHeight - clientHeight,
            behavior: 'smooth'
        });
    }
  }, [forumMessages]);

  // --- FITUR 1: GENERATE PDF DARI LKPD ---
  const handleGeneratePDF = async () => {
    setIsGenerating(true);

    try {
        const groupData: any = await getGroupData(groupName);
        
        if (!groupData || !groupData.lkpd) {
            alert("Data LKPD belum ditemukan! Silakan isi LKPD terlebih dahulu.");
            setIsGenerating(false);
            return;
        }

        const lkpd = groupData.lkpd;
        const doc = new jsPDF();
        
        doc.setFontSize(18);
        doc.text("LAPORAN HASIL INVESTIGASI", 105, 20, { align: "center" });
        
        doc.setFontSize(12);
        doc.text(`Kelompok: ${groupName}`, 20, 35);
        doc.text(`Tanggal: ${new Date().toLocaleDateString()}`, 20, 42);

        doc.setLineWidth(0.5);
        doc.line(20, 45, 190, 45);

        let yPos = 55;
        const addSection = (title: string, content: string) => {
            doc.setFont("helvetica", "bold");
            doc.text(title, 20, yPos);
            yPos += 7;
            
            doc.setFont("helvetica", "normal");
            const splitText = doc.splitTextToSize(content || "-", 170);
            doc.text(splitText, 20, yPos);
            yPos += (splitText.length * 7) + 10;
        };

        addSection("A. Variabel Penelitian", lkpd.variabel);
        addSection("B. Alat & Bahan", lkpd.alatBahan);
        addSection("C. Analisis Mekanisme", lkpd.mekanisme);
        addSection("D. Evaluasi Data", lkpd.evaluasi);
        addSection("E. Kesimpulan (Draft)", lkpd.draft);

        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by Media Pembelajaran GI - Biology UM", 105, 280, { align: "center" });

        doc.save(`Laporan_${groupName.replace(/\s+/g, '_')}.pdf`);
        setIsUploaded(true);
        alert("Laporan berhasil di-generate dari LKPD dan siap dipresentasikan!");

    } catch (error) {
        console.error("Gagal generate PDF:", error);
        alert("Terjadi kesalahan saat mengambil data LKPD.");
    } finally {
        setIsGenerating(false);
    }
  };

  // --- FITUR 2: KIRIM PESAN FORUM ---
  const handlePostComment = async (e: React.FormEvent) => {
    e.preventDefault();
    if(!newComment.trim() || !groupName) return;

    const tempMsg = { _id: Date.now().toString(), groupName, userName, message: newComment, createdAt: new Date().toISOString() };
    setForumMessages([...forumMessages, tempMsg]);
    setNewComment('');
    await sendForumMessage(groupName, userName, tempMsg.message);
  };

  const handleNext = () => {
    if(!isUploaded) return alert('Harap generate laporan kelompok terlebih dahulu!');
    router.push('/evaluasi');
  };

  return (
    <div className="min-h-screen bg-[#f7fdf9] font-sans pb-28">
      <nav className="bg-white px-6 py-4 shadow-sm flex items-center gap-4 sticky top-0 z-10 border-b border-emerald-100">
        <Link href="/investigasi" className="p-2 hover:bg-emerald-50 rounded-full text-emerald-600 transition"><ArrowLeft size={20} /></Link>
        <div><h1 className="font-bold text-emerald-900 text-lg">Presentasi & Diskusi</h1><p className="text-xs text-slate-500">Fase 4 & 5: Analisis & Evaluasi</p></div>
      </nav>

      <main className="max-w-6xl mx-auto px-6 py-8 grid md:grid-cols-2 gap-8">
        
        {/* KOLOM KIRI */}
        <div className="space-y-8">
            {/* 1. AUTO GENERATE PDF */}
            <section className="bg-white p-6 rounded-2xl shadow-sm border border-emerald-100">
                <div className="flex items-center gap-2 mb-4 text-emerald-800 border-b border-emerald-50 pb-2">
                    <FileDown size={20} />
                    <h3 className="font-bold text-lg">Hasil Investigasi (LKPD)</h3>
                </div>
                
                {!isUploaded ? (
                    <div className="flex flex-col items-center justify-center p-8 bg-emerald-50/50 rounded-xl border-2 border-dashed border-emerald-200">
                        <FileText size={48} className="text-emerald-300 mb-3" />
                        <p className="text-sm text-slate-600 text-center mb-5 max-w-xs">
                            Sistem akan otomatis mengambil data yang sudah kalian isi di halaman LKPD dan mengubahnya menjadi PDF.
                        </p>
                        <button 
                            onClick={handleGeneratePDF}
                            disabled={isGenerating}
                            className="bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-3 rounded-full font-bold shadow-lg flex items-center gap-2 transition transform active:scale-95 disabled:opacity-70"
                        >
                            {isGenerating ? <Loader2 className="animate-spin" size={18}/> : <RefreshCcw size={18}/>}
                            {isGenerating ? "Mengambil Data..." : "Generate PDF & Upload"}
                        </button>
                    </div>
                ) : (
                    <div className="bg-emerald-100 border border-emerald-200 rounded-xl p-4 flex items-center justify-between animate-in fade-in zoom-in">
                        <div className="flex items-center gap-3">
                            <div className="bg-white p-2 rounded-lg text-red-500 shadow-sm"><FileText size={24}/></div>
                            <div>
                                <p className="font-bold text-emerald-900 text-sm truncate max-w-37.5">Laporan_{groupName}.pdf</p>
                                <p className="text-xs text-emerald-600 flex items-center gap-1"><UserCheck size={12}/> Siap Dipresentasikan</p>
                            </div>
                        </div>
                        <button onClick={handleGeneratePDF} className="text-xs bg-white/50 hover:bg-white text-emerald-700 px-3 py-1 rounded-full transition">Update</button>
                    </div>
                )}
            </section>

            {/* 2. REALTIME PEER ASSESSMENT */}
            <section className="bg-white p-6 rounded-2xl shadow-sm border border-emerald-100">
                <div className="flex items-center gap-2 mb-4 text-emerald-800 border-b border-emerald-50 pb-2">
                    <Star size={20} />
                    <h3 className="font-bold text-lg">Penilaian Antar Kelompok</h3>
                </div>
                <p className="text-sm text-slate-500 mb-4">Berikan nilai (1-100) untuk presentasi kelompok lain yang tampil.</p>
                
                <div className="space-y-3 max-h-60 overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-emerald-100">
                    {otherGroups.length === 0 ? (
                        <div className="text-center p-4 bg-slate-50 rounded-xl border border-slate-100">
                            <p className="text-xs text-slate-400">Menunggu kelompok lain mendaftar...</p>
                        </div>
                    ) : (
                        otherGroups.map((gName, idx) => (
                            <div key={idx} className="flex items-center justify-between bg-slate-50 p-3 rounded-xl border border-slate-200">
                                <span className="font-bold text-slate-700 text-xs truncate max-w-37.5" title={gName}>{gName}</span>
                                <div className="flex items-center gap-2">
                                    <input 
                                        type="number" min="0" max="100" 
                                        className="w-16 p-1.5 rounded-lg border border-slate-300 text-center text-slate-800 text-sm focus:ring-2 focus:ring-emerald-400 outline-none"
                                        placeholder="0"
                                        onChange={(e) => setPeerScore({...peerScore, [gName]: parseInt(e.target.value)})}
                                    />
                                    <span className="text-xs text-slate-400">Pts</span>
                                </div>
                            </div>
                        ))
                    )}
                </div>
            </section>
        </div>

        {/* KOLOM KANAN: FORUM DISKUSI */}
        <div className="space-y-8 h-150 flex flex-col">
            <section className="bg-white p-6 rounded-2xl shadow-sm border border-emerald-100 h-full flex flex-col relative overflow-hidden">
                <div className="flex items-center gap-2 mb-4 text-emerald-800 border-b border-emerald-50 pb-2">
                    <MessageSquare size={20} />
                    <div><h3 className="font-bold text-lg leading-tight">Forum Tanya Jawab</h3><p className="text-[10px] text-emerald-500">Live Global Chat</p></div>
                </div>

                <div className="bg-yellow-50 border border-yellow-100 p-4 rounded-xl mb-4 shrink-0">
                    <div className="flex items-center gap-2 mb-2"><div className="w-6 h-6 bg-yellow-200 rounded-full flex items-center justify-center text-[10px] font-bold text-yellow-800">G</div><span className="font-bold text-yellow-800 text-xs">Komentar Guru</span></div>
                    <p className="text-sm text-slate-700 italic">"Perhatikan sesi presentasi teman kalian. Silakan bertanya melalui forum ini!"</p>
                </div>

                {/* AREA CHAT YANG DIPERBAIKI SCROLLNYA */}
                <div 
                    ref={chatContainerRef} // Ref dipindah ke container
                    className="flex-1 space-y-4 mb-4 overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-emerald-100 pb-4"
                >
                    {forumMessages.length === 0 && (
                        <p className="text-center text-sm text-slate-400 mt-10">Belum ada diskusi kelas. Jadilah yang pertama bertanya!</p>
                    )}
                    {forumMessages.map((com) => {
                        const isMe = com.groupName === groupName;
                        return (
                            <div key={com._id} className={`p-3 rounded-xl text-sm shadow-sm ${isMe ? 'bg-emerald-50 ml-8 border border-emerald-200' : 'bg-slate-50 mr-8 border border-slate-200'}`}>
                                <div className={`font-bold text-[11px] mb-1 ${isMe ? 'text-emerald-700' : 'text-slate-600'}`}>[{com.groupName}] - {com.userName}</div>
                                <div className="text-slate-800">{com.message}</div>
                                <div className="text-[9px] text-slate-400 mt-1 text-right">{new Date(com.createdAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</div>
                            </div>
                        );
                    })}
                </div>

                <form onSubmit={handlePostComment} className="mt-auto shrink-0 pt-2 border-t border-slate-50">
                    <div className="flex gap-2">
                        <input type="text" className="flex-1 bg-slate-100 border-0 rounded-full px-4 py-3 text-slate-800 text-sm focus:ring-2 focus:ring-emerald-400 outline-none" placeholder="Tulis pertanyaan..." value={newComment} onChange={(e) => setNewComment(e.target.value)} />
                        <button type="submit" disabled={!newComment.trim()} className="bg-emerald-500 hover:bg-emerald-600 text-white p-3 rounded-full shadow-md transition transform active:scale-95"><Send size={18} /></button>
                    </div>
                </form>
            </section>
        </div>
      </main>

      <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-emerald-100 p-4 shadow-[0_-5px_20px_rgba(0,0,0,0.05)] z-30">
        <div className="max-w-5xl mx-auto flex justify-between items-center">
            <div className="hidden md:block text-xs text-slate-500">Pastikan presentasi selesai sebelum lanjut evaluasi.</div>
            <button onClick={handleNext} className="w-full md:w-auto bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 px-8 rounded-full shadow-lg flex items-center justify-center gap-2 transition-all transform active:scale-95">Lanjut ke Evaluasi <ArrowRight size={20} /></button>
        </div>
      </div>
    </div>
  );
}